export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';

export const STATUS_REQUEST = 'STATUS_REQUEST';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_REJECT = 'STATUS_REJECT';

export const LOGOUT = 'LOGOUT';

export const TOGGLE_AUTH_DROPDOWN = 'TOGGLE_AUTH_DROPDOWN';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

export const LOAD_CHANNELS_REQUEST = 'LOAD_CHANNELS_REQUEST';
export const LOAD_CHANNELS_SUCCESS = 'LOAD_CHANNELS_SUCCESS';
export const LOAD_CHANNELS_ERROR = 'LOAD_CHANNELS_ERROR';

export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST';
export const CHANNEL_CREATED = 'CHANNEL_CREATED';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';

export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const NEW_MESSAGE = 'NEW_MESSAGE';